name: Integración Continua

on:
  push:
    branches:
      - devops

env:
  AWS_REGION: us-east-1

jobs:
  # --- TRABAJO 1: TESTEAR EL BACKEND (JAVA) ---
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Backend Tests (Despacho)
        run: |
          cd back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          chmod +x mvnw
          ./mvnw test

      - name: Run Backend Tests (Venta)
        run: |
          cd back-Ventas_SpringBoot/Springboot-API-REST
          chmod +x mvnw
          ./mvnw test

  # --- TRABAJO 2: TESTEAR EL FRONTEND (REACT) ---
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './front_despacho/package-lock.json'

      - name: Install Dependencies
        run: |
          cd front_despacho
          npm install

      - name: Run Frontend Tests
        run: |
          cd front_despacho
          # Nota: En entornos de CI (como GitHub Actions), el comando 'npm test' de React suele quedarse escuchando cambios (watch mode). 
          # Añadimos CI=true para que corra los tests una vez y termine el proceso.
          CI=true npm test

      - name: Obtener dirección del Load Balancer
        run: |
          kubectl get service frontend-despacho -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' || echo "Buscando dirección..."